
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  <<: *default
  database: expert-todo_development

test:
  <<: *default
  database: expert-todo_test

production:
 url: <%= ENV['DATABASE_URL'] %>
